global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: ''
        from: ''
        smarthost: ':587'
        auth_username: ''
        auth_identity: ''
        auth_password: ''
        require_tls: true
        send_resolved: true
