global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'logesh@sixthstar.in'
        from: 'logesh@sixthstar.in'
        smarthost: 'star.sixthstar.in:587'
        auth_username: 'logesh@sixthstar.in'
        auth_identity: 'logesh@sixthstar.in'
        auth_password: 'Mlogan@123#'
        require_tls: true
        send_resolved: true
